#!/usr/bin/env python3
"""
Generate the Appendix B point-list tables for the final report from the Excel
workbook. Reads PLC/Point List.xlsx and writes docs/appendix_pointlist.tex, which
the report \input{}s. Every sheet becomes a landscape, full-grid table using the
spreadsheet's columns (Point Description, Origin Address, DO/DI/AO/AI/Pwr,
Destination Address, Destination Description, Notes).

Usage (from repo root or docs/):
    python3 docs/gen_pointlist.py            # uses default paths
    python3 docs/gen_pointlist.py PLC/Point\\ List.xlsx docs/appendix_pointlist.tex

Requires: openpyxl  (pip install openpyxl)
"""
import sys
import openpyxl

XLSX = sys.argv[1] if len(sys.argv) > 1 else "PLC/Point List.xlsx"
OUT  = sys.argv[2] if len(sys.argv) > 2 else "docs/appendix_pointlist.tex"

# Unicode -> LaTeX replacements for spreadsheet text
UNI = {
    '—': '--', '–': '--', '‒': '--', '″': "''", '′': "'",
    '→': r'$\rightarrow$', '←': r'$\leftarrow$',
    '≥': r'$\geq$', '≤': r'$\leq$',
    'Ω': r'$\Omega$', '°': r'\textdegree{}', 'µ': r'$\mu$',
    '×': r'$\times$', '…': '...', '•': r'\textbullet{}',
    '“': "``", '”': "''", '‘': "`", '’': "'",
    ' ': ' ', '±': r'$\pm$',
}

def esc(v):
    if v is None:
        return ''
    s = str(v)
    if s.strip() == '':
        return ''
    for u, r in UNI.items():
        s = s.replace(u, r)
    out = []
    for ch in s:
        if ch in '&%$#_{}':
            out.append('\\' + ch)
        elif ch == '~': out.append(r'\textasciitilde{}')
        elif ch == '^': out.append(r'\textasciicircum{}')
        elif ch == '\\': out.append(r'\textbackslash{}')
        elif ch == '>': out.append(r'\textgreater{}')
        elif ch == '<': out.append(r'\textless{}')
        else: out.append(ch)
    return ''.join(out)

def cell(ws, r, c):
    return ws.cell(row=r, column=c).value

def num(v):
    if v is None:
        return ''
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)

COLSPEC = r'|p{3.0cm}|p{1.25cm}|c|c|c|c|c|p{2.5cm}|p{4.0cm}|X|'
HEADERS = ['Point Description', 'Origin', 'DO', 'DI', 'AO', 'AI', 'Pwr',
           'Destination Address', 'Destination Description', 'Notes']

def header_block():
    h = ' & '.join(r'\textbf{%s}' % x for x in HEADERS)
    return ('\\hline\n\\rowcolor{PSUgreen!12}' + h + ' \\\\\n\\hline\n\\endfirsthead\n'
            '\\hline\n\\rowcolor{PSUgreen!12}' + h + ' \\\\\n\\hline\n\\endhead\n')

def find_header_row(ws):
    for r in range(1, min(ws.max_row, 8) + 1):
        for c in range(1, ws.max_column + 1):
            v = cell(ws, r, c)
            if v and 'Point Description' in str(v):
                return r
    return None

def emit_standard(ws, hr, ncols):
    # 11-col sheets carry an extra "virtual point" column (skip col 8)
    cmap = [1, 2, 3, 4, 5, 6, 7, 9, 10, 11] if ncols >= 11 else [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    rows = []
    for r in range(hr + 1, ws.max_row + 1):
        vals = [cell(ws, r, c) for c in cmap]
        if all(v is None or str(v).strip() == '' for v in vals):
            continue
        cells = ([esc(vals[0]), esc(vals[1])]
                 + [num(vals[i]) for i in range(2, 7)]
                 + [esc(vals[7]), esc(vals[8]), esc(vals[9])])
        rows.append(' & '.join(cells) + r' \\ \hline')
    return rows

def emit_generic(ws):
    maxc = min(ws.max_column, 6)
    rows = []
    for r in range(1, ws.max_row + 1):
        vals = [cell(ws, r, c) for c in range(1, maxc + 1)]
        if all(v is None or str(v).strip() == '' for v in vals):
            continue
        rows.append(' & '.join(esc(v) for v in vals) + r' \\ \hline')
    return rows, maxc

def main():
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    out = ['% Auto-generated by gen_pointlist.py from PLC/Point List.xlsx -- do not edit by hand.',
           r'\begingroup', r'\footnotesize', r'\setlength{\tabcolsep}{3pt}',
           r'\renewcommand{\arraystretch}{1.15}', r'\begin{landscape}']
    for nm in wb.sheetnames:
        ws = wb[nm]
        out.append('')
        out.append(r'\noindent\textbf{\textcolor{PSUgreen}{Sheet: %s}}\par\smallskip' % esc(nm))
        hr = find_header_row(ws)
        if hr is None:
            rows, maxc = emit_generic(ws)
            spec = '|' + '|'.join(['p{4cm}'] * (maxc - 1) + ['X']) + '|' if maxc > 1 else '|X|'
            out += [r'\begin{xltabular}{\linewidth}{%s}' % spec, r'\hline'] + rows + [r'\end{xltabular}']
        else:
            rows = emit_standard(ws, hr, ws.max_column)
            out += [r'\begin{xltabular}{\linewidth}{%s}' % COLSPEC, header_block()] + rows + [r'\end{xltabular}']
        out.append(r'\vspace{6pt}')
    out += [r'\end{landscape}', r'\endgroup']
    with open(OUT, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print('Wrote %s (%d sheets)' % (OUT, len(wb.sheetnames)))

if __name__ == '__main__':
    main()
